### ISSUE TITLE
 Update Business Primer by Fixing the "confidential" and "https" Bits and Upload to the website

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#102]

**Comment by Shadowfiend** [comment]
Ditto here, are we trying to upload a new version?

**Comment by elizapetrovska** [comment]
Yes:)
[Keep-Business-Primer_2019-3-20.pdf](https://github.com/keep-network/website/files/2996769/Keep-Business-Primer_2019-3-20.pdf)

**Comment by Gluzman** [comment]
Erin needs to help I think... unless someone can show me how/where.

**Comment by ironng** [comment]
I can do this! @elizapetrovska this is ready to go on the site? (is the "confidential" bit fixed already?)

**Comment by elizapetrovska** [comment]
Oh nice, thanks Erin! No, will ping you here when it is :)

**Comment by Gluzman** [comment]
https-ed
<img width="719" alt="Screen Shot 2019-03-26 at 12 13 37" src="https://user-images.githubusercontent.com/7621557/55014011-a5790e00-4fc0-11e9-943e-73a62bbbcefb.png">

**Comment by Gluzman** [comment]
LA (Un)confidential
<img width="136" alt="Screen Shot 2019-03-26 at 13 00 31" src="https://user-images.githubusercontent.com/7621557/55017759-c98c1d80-4fc7-11e9-92d6-d528c7286126.png">
<img width="383" alt="Screen Shot 2019-03-26 at 13 00 23" src="https://user-images.githubusercontent.com/7621557/55017760-c98c1d80-4fc7-11e9-9fe7-2e7f6831a585.png">

**Comment by Gluzman** [comment]
updated PDF
[Keep-Business-Primer_2019-3-26.pdf](https://github.com/keep-network/website/files/3009325/Keep-Business-Primer_2019-3-26.pdf)

**Comment by elizapetrovska** [comment]
cc @ironng , ready now!

**Comment by Shadowfiend** [comment]
@Gluzman Just for reference, how do we update the primer in the future? Do we have to go through you? Where does the source file live?

**Comment by Gluzman** [comment]
@Shadowfiend, first to answer your Q: updating the primer would need to go thru me for now (or someone with knowledge of layout design with Adobe Indesign). The file currently resides in the Thesis Dropbox. The original copy used for the content was written in Google Docs.

I bet you're wondering: how might we make the doc more accessible and updatable by anyone? well, it's a bigger Q—we have many things at the co. where not everyone can just update or do something with. we first need to understand who may need to, how often, what is likely to change, tool competencies, and more i'm probably not thinking of...and then we could design for the ability to update without a single point of failure. Not to mention, some form of version control....

this is a topic that comes up in every company ever. the desire to have non-generic, hard-to-fake docs editable by anyone. that's a tough gap to fill. so let's talk more about it...because i am not sure I've come across a great answer.

**Comment by elizapetrovska** [comment]
Michael, so this is not in Keynote now? Just FYI - I don't mind to keep doing it, as I was up to now with the old version. One thing is that the photos are a bit more sophisticated now :)

**Comment by Gluzman** [comment]
It is no longer in Keynote. The photos are actually still pretty easy—just drag and drop in, but the grid system of the layout is more sophisticated.
ie.
<img width="638" alt="Screen Shot 2019-03-27 at 12 22 52" src="https://user-images.githubusercontent.com/7621557/55093600-0e2cbd00-508b-11e9-9225-ab8bfbd543c2.png">

**Comment by Shadowfiend** [comment]
I see I accidentally forked this conversation into two places, sorry <_<

I hear you re: the questions we should be asking. Something worth bringing up at the next planning meeting, perhaps.
