### ISSUE TITLE
Upload the new Primer to the website

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#143]
see the PDF attached

**Comment by elizapetrovska** [comment]
[Keep Business Primer.pdf](https://github.com/keep-network/website/files/3483300/Keep.Business.Primer.pdf)

**Comment by elizapetrovska** [comment]
@Shadowfiend not going to put it into the sprint, depending on your availability. Please suggest if I should assign someone else!

**Comment by Shadowfiend** [comment]
This is pretty trivial to do, not certain I can get it today but I'm going to try.

**Comment by Shadowfiend** [comment]
Okay, nailed it.

@elizapetrovska next time we need to update the business primer, you can go to https://github.com/keep-network/website/tree/master/public and hit “Upload Files” (or go straight to https://github.com/keep-network/website/upload/master/public) and drag the primer in, then do a commit message the way you usually do with Slack updates and such and open a PR.

Of note! The file has to be named `KeepBusinessPrimer.pdf`, otherwise it won't properly update the existing one.

**Comment by elizapetrovska** [comment]
Great! Thank you!
