### ISSUE TITLE
Map staking resource center paths - self v. provider

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#195]
As a a user who wants to know how to get started in the stakedrop. You arrive at our staking resource center and you would: 
- encounter info that gives you an overview of staking requirements
- based on that basic info there are 3 possible paths (we think): 
1. user goes down at-home staking path and succeeds
2. user attempts at-home staking & decides to go to a provider instead (for time or hardware roadblocks, not because they couldn't find the information/troubleshoot)
3. user immediately knows they can't/don't want to meet the technical requirements, and chooses the staking provider path first

We want to make no. 3 the least attractive as possible, but we do want this information to be available.

**Comment by creckhow** [comment]
@liz-shinn primarily and @Gluzman -- this issue is a UX question. IMO it could be path designed via keep.network journey, via the gitbook IA, or both/combination. This is related to #196 since we've decided gitbook will be a large portion of our v1 solution. 

Let me know if the description needs more work, if you think we need to break this down more, or if this should be de-prioritized or combined with another issue.

**Comment by creckhow** [comment]
also pinging @sthompson22 and @mhluongo on this one, it's got larger strategic/tech implications

**Comment by creckhow** [comment]
Liz: "to me this flow IS the stakedrop page...ppl asking what is this, do I want to do it myself, do I want to use a provider"

**Comment by liz-shinn** [comment]
Included with the launch of the new Keep website design and strategy, closing this issue.
