### ISSUE TITLE
Update banner at the top of the site

### ISSUE THREAD

**Issue by mhluongo** [keep-network/website#212]
From @Gluzman, this adds a little more tBTC brand recognition and drives people to chat about the stakedrop

<img width="831" alt="Screen Shot 2020-07-19 at 11 12 10" src="https://user-images.githubusercontent.com/427505/87882866-30112800-c9d1-11ea-9937-269f65f1fd08.png">

**Comment by Shadowfiend** [comment]
Realized that although this was largely text, there's an image component to be factored in. Reopening.

**Comment by liz-shinn** [comment]
Updating this per @Gluzman 
>i like dismissible. it's the better pattern. and it ideally should not be sticky... or not part of nav?
conversely, we ought to consider the info in the banner as more temporary, and if we're putting info we need to be more permanent, this [full width] banner pattern isn't the right solution.

<img width="855" alt="Screen Shot 2020-07-20 at 8 54 19 PM" src="https://user-images.githubusercontent.com/57226633/87974959-32f04380-cacb-11ea-8ba3-f6cc17b5c15c.png">
Fixes:
- It's not fixed to navigation. Before, the sticky navigation was taking up significant screen real estate when this banner is included
- It's dismissible, since this is meant to be temporary info. If it is more permanent, like Michael is saying above, we should move this / a different solution
- It's not full width and is more prominent, central location beneath nav
